version: "2.3"
networks:
  internal_network:
services:
  mysql:
    restart: always
    networks:
      - internal_network
    #network_mode: bridge
    image: mysql:5.7.27
    environment:
      - MYSQL_ROOT_PASSWORD=gmtools
    volumes:
      - ~/docker/mysql:/var/lib/mysql
    expose:
      - "3306"
    ports:
      - "3307:3306"
  phpmyadmin:
    restart: always
    #network_mode: bridge
    image: phpmyadmin/phpmyadmin:4.7.9-1
    links:
      - "mysql"
    environment:
      - PMA_HOST=mysql
    volumes:
      - ~/Documents/Kitematic/mysql:/var/lib/mysql
    expose:
      - "80"
    ports:
      - "1801:80"
  dzzoffice:
    restart: always
    networks:
      - internal_network
    #network_mode: bridge
    image: land007/dzzoffice:latest
    links:
      - "mysql"
    expose:
      - "80"
    #ports:
      #- "1800:80"
  onlyoffice:
    image: land007/documentserver:latest
    restart: always
    networks:
      - internal_network
    #network_mode: bridge
    expose:
      - "80"
    #ports:
      #- "8000:80"
  collabora:
    image: collabora/code:latest
    restart: always
    networks:
      - internal_network
    #network_mode: bridge
    expose:
      - "9980"
    ports:
      - "9980:9980"
    environment:
      - username=admin
      - password=S3cRet
  http-proxy:
    image: land007/http-proxy:latest
    restart: always
    networks:
      - internal_network
    #network_mode: bridge
    links:
      - "dzzoffice"
      - "onlyoffice"
    expose:
      - "80"
    ports:
      - "1800:80"
    environment:
      - http_proxy_domains=msa.gjxt.xyz:2324,msa.gjxt.xyz:2324,msa.gjxt.xyz:2324,msa.gjxt.xyz:2324,msa.gjxt.xyz:2324
      - http_proxy_paths=/web-apps/apps/api/documents/api.js,/web-apps/,/5.4.2-46//,/cache/files/,/
      - http_proxy_hosts=onlyoffice,onlyoffice,onlyoffice,onlyoffice,dzzoffice
      - http_proxy_ports=80,80,80,80,80
      - http_proxy_pretends=true,false,true,true,false
      - ws_proxy_domains=msa.gjxt.xyz:2324
      - ws_proxy_paths=/
      - ws_proxy_hosts=onlyoffice
      - ws_proxy_ports=80
      - password=

#docker cp dzz.tar.gz dzzoffice-master_dzzoffice_1:/var/www/html
#docker exec -it dzzoffice-master_dzzoffice_1 bash
#tar -zxvf dzz.tar.gz

#OnlyOffice Document Server API地址:
#/web-apps/apps/api/documents/api.js
#文件服务器(dzzoffice服务器)地址:
#http://dzzoffice/

#unset ${!DOCKER_*}
#sudo docker-compose up -d
#sudo docker-compose down

#防火墙
#[root@liang ~]# firewall-cmd --zone=public --add-port=1800/tcp --permanent
#[root@liang ~]# firewall-cmd --reload
#文件存放地址
#/var/www/html/data/attachment/dzz/
